public struct Repository: Codable {
    public let id: Int
    public let nodeId: String
    public let name: String
    public let fullName: String
    public let `private`: Bool
    public let owner: User
    public let htmlUrl: String
    public let description: String?
    public let fork: Bool
    public let url: String
    public let forksUrl: String
    public let keysUrl: String
    public let collaboratorsUrl: String
    public let teamsUrl: String
    public let hooksUrl: String
    public let issueEventsUrl: String
    public let eventsUrl: String
    public let assigneesUrl: String
    public let branchesUrl: String
    public let tagsUrl: String
    public let blobsUrl: String
    public let gitTagsUrl: String
    public let gitRefsUrl: String
    public let treesUrl: String
    public let statusesUrl: String
    public let languagesUrl: String
    public let stargazersUrl: String
    public let contributorsUrl: String
    public let subscribersUrl: String
    public let subscriptionUrl: String
    public let commitsUrl: String
    public let gitCommitsUrl: String
    public let commentsUrl: String
    public let issueCommentUrl: String
    public let contentsUrl: String
    public let compareUrl: String
    public let mergesUrl: String
    public let archiveUrl: String
    public let downloadsUrl: String
    public let issuesUrl: String
    public let pullsUrl: String
    public let milestonesUrl: String
    public let notificationsUrl: String
    public let labelsUrl: String
    public let releasesUrl: String
    public let deploymentsUrl: String
    public let createdAt: String
    public let updatedAt: String
    public let pushedAt: String
    public let gitUrl: String
    public let sshUrl: String
    public let cloneUrl: String
    public let svnUrl: String
    public let homepage: String?
    public let size: Int
    public let stargazersCount: Int
    public let watchersCount: Int
    public let language: String?
    public let hasIssues: Bool
    public let hasProjects: Bool
    public let hasDownloads: Bool
    public let hasWiki: Bool
    public let hasPages: Bool
    public let forksCount: Int
    public let mirrorUrl: String?
    public let archived: Bool
    public let disabled: Bool
    public let openIssuesCount: Int
    public let license: String?
    public let forks: Int
    public let openIssues: Int
    public let watchers: Int
    public let defaultBranch: String
}
